/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRecentRouteImport } from './routes/_app/recent'
import { Route as AppFavouritesRouteImport } from './routes/_app/favourites'
import { Route as AppRecordingRecordingIdRouteImport } from './routes/_app/recording.$recordingId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecentRoute = AppRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => AppRoute,
} as any)
const AppFavouritesRoute = AppFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordingRecordingIdRoute = AppRecordingRecordingIdRouteImport.update({
  id: '/recording/$recordingId',
  path: '/recording/$recordingId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/favourites': typeof AppFavouritesRoute
  '/recent': typeof AppRecentRoute
  '/': typeof AppIndexRoute
  '/recording/$recordingId': typeof AppRecordingRecordingIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/favourites': typeof AppFavouritesRoute
  '/recent': typeof AppRecentRoute
  '/': typeof AppIndexRoute
  '/recording/$recordingId': typeof AppRecordingRecordingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/favourites': typeof AppFavouritesRoute
  '/_app/recent': typeof AppRecentRoute
  '/_app/': typeof AppIndexRoute
  '/_app/recording/$recordingId': typeof AppRecordingRecordingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/favourites'
    | '/recent'
    | '/'
    | '/recording/$recordingId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/favourites' | '/recent' | '/' | '/recording/$recordingId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/favourites'
    | '/_app/recent'
    | '/_app/'
    | '/_app/recording/$recordingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recent': {
      id: '/_app/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof AppRecentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favourites': {
      id: '/_app/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof AppFavouritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recording/$recordingId': {
      id: '/_app/recording/$recordingId'
      path: '/recording/$recordingId'
      fullPath: '/recording/$recordingId'
      preLoaderRoute: typeof AppRecordingRecordingIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFavouritesRoute: typeof AppFavouritesRoute
  AppRecentRoute: typeof AppRecentRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRecordingRecordingIdRoute: typeof AppRecordingRecordingIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFavouritesRoute: AppFavouritesRoute,
  AppRecentRoute: AppRecentRoute,
  AppIndexRoute: AppIndexRoute,
  AppRecordingRecordingIdRoute: AppRecordingRecordingIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
