/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRecordRouteImport } from './routes/_app/record'
import { Route as AppRecordingRecordingIdRouteImport } from './routes/_app/recording.$recordingId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordRoute = AppRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordingRecordingIdRoute = AppRecordingRecordingIdRouteImport.update({
  id: '/recording/$recordingId',
  path: '/recording/$recordingId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/record': typeof AppRecordRoute
  '/': typeof AppIndexRoute
  '/recording/$recordingId': typeof AppRecordingRecordingIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/record': typeof AppRecordRoute
  '/': typeof AppIndexRoute
  '/recording/$recordingId': typeof AppRecordingRecordingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/record': typeof AppRecordRoute
  '/_app/': typeof AppIndexRoute
  '/_app/recording/$recordingId': typeof AppRecordingRecordingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/record' | '/' | '/recording/$recordingId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/record' | '/' | '/recording/$recordingId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/record'
    | '/_app/'
    | '/_app/recording/$recordingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/record': {
      id: '/_app/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof AppRecordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recording/$recordingId': {
      id: '/_app/recording/$recordingId'
      path: '/recording/$recordingId'
      fullPath: '/recording/$recordingId'
      preLoaderRoute: typeof AppRecordingRecordingIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppRecordRoute: typeof AppRecordRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRecordingRecordingIdRoute: typeof AppRecordingRecordingIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppRecordRoute: AppRecordRoute,
  AppIndexRoute: AppIndexRoute,
  AppRecordingRecordingIdRoute: AppRecordingRecordingIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
